// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Order.Databases;

#nullable disable

namespace Order.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20260908092619_RemoveOutboxDispatchedAt")]
    partial class RemoveOutboxDispatchedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FxLink.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("DelayTime")
                        .HasColumnType("interval");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<Guid>("PartitionKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScheduleToken")
                        .HasColumnType("uuid");

                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Sequence"));

                    b.Property<string>("SerializedHeaders")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TimeToLive")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("PartitionKey", "Sequence");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("FxLink.Outbox.EntityFrameworkCore.Entities.OutboxPartitionLease", b =>
                {
                    b.Property<Guid>("PartitionKey")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LeasedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PartitionKey");

                    b.ToTable("OutboxPartitionLease");
                });
#pragma warning restore 612, 618
        }
    }
}
